# Exported from Render on 2024-08-09T19:38:17Z
services:
- type: web
  name: p_manage
  runtime: python
  repo: https://github.com/temmytope88/p_manage
  plan: free
  region: oregon
  buildCommand: pip install -r requirements.txt
  startCommand: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
  pullRequestPreviewsEnabled: true
version: "1"
